# -*- coding: utf-8 -*-
"""Reto #1: EL "LENGUAJE HACKER"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13-9QbB2rtFK0Zo0vJNRyDkCOVk2bpXg_
"""

'''
 * Escribe un programa que reciba un texto y transforme lenguaje natural a
 * "lenguaje hacker" (conocido realmente como "leet" o "1337"). Este lenguaje
 *  se caracteriza por sustituir caracteres alfanuméricos.
 * - Utiliza esta tabla (https://www.gamehouse.com/blog/leet-speak-cheat-sheet/) 
 *   con el alfabeto y los números en "leet".
 *   (Usa la primera opción de cada transformación. Por ejemplo "4" para la "a")
'''

def translator_hacker(plain_text):
  plain_text=plain_text.lower()
  leet=['4','I3','[',')','3','|=','&','#','1',',_|','>|','1','JVI','^/','0','|*','(_,)','I2','5','7','(_)','\/','\/\/','><','j','2','L','R','E','A','S','b','T','B','g','o']
  alphabet="abcdefghijklmnopqrstuvwxyz1234567890"
  hacker_text = ""
  for char in plain_text:
    if char in alphabet:
      char_index = alphabet.index(char)
      hacker_text+=leet[char_index]
    else:
      hacker_text += char
  return hacker_text

translator_hacker('!HOLA cómo estás 134')