# -*- coding: utf-8 -*-
"""012_Viernes13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YdJb2Htw90LdLOxZtqyIRukDH3iDMTWp
"""

'''
 * Crea una función que sea capaz de detectar si existe un viernes 13 en el mes y el año indicados.
 * - La función recibirá el mes y el año y retornará verdadero o falso.
'''

!pip install datetime
from datetime import date

def viernes_13(mes, anyo):

  return date(year = anyo, month = mes, day = 13).weekday() == 4

while True:
  try:
    mes = int(input('Introduce el mes: '))
    anyo = int(input('Introduce el año: '))
    break

  except:
    print('Error. Debes introducir NÚMERO de mes y año.')

viernes_13(mes, anyo)