fun main() {
    switchToHackerLanguaje("Hola hackerman!")
}

fun switchToHackerLanguaje(text: String) {
    val result = text.lowercase(Locale.getDefault())
        .replace('a', '4')
        .replace("b", "I3")
        .replace('c', '[')
        .replace('d', ')')
        .replace('e', '3')
        .replace("f", "|=")
        .replace('g', '&')
        .replace('h', '#')
        .replace('i', '1')
        .replace("j", ",_|")
        .replace("k", ">|")
        .replace('l', '1')
        .replace("m", "/\\/\\")
        .replace("n", "^/")
        .replace('o', '0')
        .replace("p", "|*")
        .replace("q", "(_,)")
        .replace("r", "I2")
        .replace('s', '5')
        .replace('t', '7')
        .replace("u", "(_)")
        .replace("v", "\\/")
        .replace("w", "\\/\\/")
        .replace("x", "><")
        .replace('y', 'j')
        .replace('z', '2')
        .replace('0', 'o')
        .replace('1', 'L')
        .replace('2', 'R')
        .replace('3', 'E')
        .replace('4', 'A')
        .replace('5', 'S')
        .replace('6', 'b')
        .replace('7', 'T')
        .replace('8', 'B')
        .replace('9', 'g')

    print(result)
}