function leetLenguaje(word) {

  const leetWord = word.toLowerCase()
    .replaceAll('1', 'L')
    .replaceAll('2', 'R')
    .replaceAll('3', 'E')
    .replaceAll('4', 'A')
    .replaceAll('5', 'S')
    .replaceAll('6', 'b')
    .replaceAll('7', 'T')
    .replaceAll('8', 'B')
    .replaceAll('9', 'g')
    .replaceAll('0', 'o')
    .replaceAll('a', '4')
    .replaceAll('b', 'I3')
    .replaceAll('c', '[')
    .replaceAll('d', ')')
    .replaceAll('e', '3')
    .replaceAll('f', '|=')
    .replaceAll('g', '&')
    .replaceAll('h', '#')
    .replaceAll('i', '1')
    .replaceAll('j', ',_|')
    .replaceAll('k', '>|')
    .replaceAll('l', '1')
    .replaceAll('m', '/\\/\\')
    .replaceAll('n', '^/')
    .replaceAll('o', '0')
    .replaceAll('p', '|*')
    .replaceAll('q', '(_,)')
    .replaceAll('r', 'I2')
    .replaceAll('s', '5')
    .replaceAll('t', '7')
    .replaceAll('u', '(_)')
    .replaceAll('v', '\/')
    .replaceAll('w', '\/\/')
    .replaceAll('x', '><')
    .replaceAll('y', 'j')
    .replaceAll('z', '2')

  return leetWord;
};

console.log(leetLenguaje('Hello word!'))

