# -*- coding: utf-8 -*-
"""Reto #2: EL PARTIDO DE TENIS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sJGL7Av5Uyc0NzngtGiPH1IjCpPOkZin
"""

'''
 * Escribe un programa que muestre cómo transcurre un juego de tenis y quién lo ha ganado.
 * El programa recibirá una secuencia formada por "P1" (Player 1) o "P2" (Player 2), según quien
 * gane cada punto del juego.
 * 
 * - Las puntuaciones de un juego son "Love" (cero), 15, 30, 40, "Deuce" (empate), ventaja.
 * - Ante la secuencia [P1, P1, P2, P2, P1, P2, P1, P1], el programa mostraría lo siguiente:
 *   15 - Love
 *   30 - Love
 *   30 - 15
 *   30 - 30
 *   40 - 30
 *   Deuce
 *   Ventaja P1
 *   Ha ganado el P1
 * - Si quieres, puedes controlar errores en la entrada de datos.   
 * - Consulta las reglas del juego si tienes dudas sobre el sistema de puntos.   
 '''

def tenis_game(secuencia):
  P1control=0
  P2control=0
  puntos=['Love','15','30','40']
  finished=False
  for i in secuencia:

    P1control+=1 if i == 'P1' else 0
    P2control+=1 if i == 'P2' else 0

    if P1control>=3 and P2control>=3:
      if abs(P1control-P2control)<=1 and not finished:
          print('Deuce' if P1control == P2control else 'Ventaja P1' if P1control>P2control else 'Ventaja P2')
      else:
        finished = True
    else:
      if P1control < 4 and P2control < 4:
        print(puntos[P1control], '-', puntos[P2control])
      else:
        finished=True
  print('Los puntos ingresados son incorrectos' if not finished else 'Ha ganado el P1' if P1control>P2control else 'Ha ganado el P2')

tenis_game(['P1', 'P1', 'P2', 'P2', 'P1', 'P2', 'P1', 'P1'])