# -*- coding: utf-8 -*-
"""Reto #0: EL FAMOSO "FIZZ BUZZ"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e-QWUO_7Zs67Cp6YEkzjBp3QKhJV5Ode

* Escribe un programa que muestre por consola (con un print) los
 * números de 1 a 100 (ambos incluidos y con un salto de línea entre
 * cada impresión), sustituyendo los siguientes:
 * - Múltiplos de 3 por la palabra "fizz".
 * - Múltiplos de 5 por la palabra "buzz".
 * - Múltiplos de 3 y de 5 a la vez por la palabra "fizzbuzz".
"""

for j in range(1,101):
    if j % 3 == 0 and j % 5 == 0:
      print('fizzbuzz')
    elif j % 5 == 0:
      print('buzz')
    elif j % 3 == 0:
      print('fizz')
    else:
      print(j)